"""Fonctions pures de normalisation (SPEC §5.2, §7.4, §8.4). Aucune dépendance au reste du moteur."""

from controldone.normalize.amounts import (
    MontantLu,
    NombreLu,
    parse_amount,
    parse_decimal,
    parse_int,
    parse_nombre,
)
from controldone.normalize.codes import code_marchandise, code_sh6
from controldone.normalize.countries import ISO2, country_to_iso2
from controldone.normalize.currency import (
    DEVISE_INCONNUE,
    DEVISES_SANS_DECIMALES,
    ISO_4217,
    codes_iso_dans_texte,
    exposant_devise,
    normalize_currency,
)
from controldone.normalize.dates import DateLue, parse_date, parse_date_detail
from controldone.normalize.fiscal import (
    cle_tva_fr,
    extraire_siren,
    normalize_eori,
    normalize_vat,
    siren_depuis_siret,
    siren_depuis_tva,
    siren_luhn_valide,
    tva_fr_depuis_siren,
    tva_fr_valide,
)
from controldone.normalize.incoterms import INCOTERMS, INCOTERMS_ANCIENS, IncotermLu, parse_incoterm
from controldone.normalize.refs import (
    est_mrn,
    mrn_egaux,
    mrn_prefixe,
    norm_ref,
    norm_ref_containment,
    norm_ref_transport,
    ref_compatibles,
    ref_egales,
    ref_transport_compatibles,
    ref_transport_egales,
)
from controldone.normalize.text import cle_texte, normaliser_espaces, sans_accents
from controldone.normalize.units import (
    UNITE_INCONNUE,
    UNITES_ENTIERES,
    UniteNormalisee,
    normalize_unit,
    parse_weight_kg,
)

__all__ = [
    "DEVISES_SANS_DECIMALES",
    "DEVISE_INCONNUE",
    "INCOTERMS",
    "INCOTERMS_ANCIENS",
    "ISO2",
    "ISO_4217",
    "UNITES_ENTIERES",
    "UNITE_INCONNUE",
    "DateLue",
    "IncotermLu",
    "MontantLu",
    "NombreLu",
    "UniteNormalisee",
    "cle_texte",
    "cle_tva_fr",
    "code_marchandise",
    "code_sh6",
    "codes_iso_dans_texte",
    "country_to_iso2",
    "est_mrn",
    "exposant_devise",
    "extraire_siren",
    "mrn_egaux",
    "mrn_prefixe",
    "norm_ref",
    "norm_ref_containment",
    "norm_ref_transport",
    "normaliser_espaces",
    "normalize_currency",
    "normalize_eori",
    "normalize_unit",
    "normalize_vat",
    "parse_amount",
    "parse_date",
    "parse_date_detail",
    "parse_decimal",
    "parse_incoterm",
    "parse_int",
    "parse_nombre",
    "parse_weight_kg",
    "ref_compatibles",
    "ref_egales",
    "ref_transport_compatibles",
    "ref_transport_egales",
    "sans_accents",
    "siren_depuis_siret",
    "siren_depuis_tva",
    "siren_luhn_valide",
    "tva_fr_depuis_siren",
    "tva_fr_valide",
]
