"""Rendu PDF des factures commerciales (en / fr / es), plusieurs mises en page."""

from __future__ import annotations

from .common import cur_decimals, d_en, d_es, d_fr, d_dot, fmt_kg, fmt_num, fmt_qty
from .pdfkit import BLUE, DARK, GREY, LIGHT, Pen
from .refdata import UNIT_LABELS

LBL = {
    "en": {"facture": "COMMERCIAL INVOICE", "pro_forma": "PROFORMA INVOICE",
           "valeur_douane_seulement": "INVOICE - VALUE FOR CUSTOMS PURPOSES ONLY",
           "facture_integrateur": "COMMERCIAL INVOICE", "no": "Invoice No.", "date": "Invoice date",
           "seller": "Seller / Exporter", "buyer": "Buyer / Bill to", "consignee": "Ship to / Consignee",
           "vat": "VAT No.", "eori": "EORI", "inc": "Incoterms", "pay": "Payment terms", "awb": "AWB No.",
           "bl": "B/L No.", "via": "Shipped via", "item": "#", "ref": "Item ref.", "desc": "Description",
           "hs": "HS code", "orig": "Orig.", "qty": "Qty", "unit": "Unit", "up": "Unit price", "amt": "Amount",
           "goods": "Subtotal (goods)", "fret": "Freight", "assurance": "Insurance", "emballage": "Packing",
           "remise": "Discount", "total": "TOTAL AMOUNT", "gross": "Total gross weight", "net": "Total net weight",
           "pk": "Number of packages", "ptot": "Page total", "cur": "Currency", "page": "Page",
           "nw": "N.W. kg", "decl": "We hereby certify that this invoice is true and correct.",
           "integ": "Generated by {c} on behalf of the shipper", "cartons": "cartons"},
    "fr": {"facture": "FACTURE COMMERCIALE", "pro_forma": "FACTURE PRO FORMA",
           "valeur_douane_seulement": "FACTURE - VALEUR POUR LA DOUANE UNIQUEMENT",
           "facture_integrateur": "FACTURE COMMERCIALE", "no": "Facture n°", "date": "Date",
           "seller": "Vendeur / Exportateur", "buyer": "Acheteur / Facturé à", "consignee": "Livré à",
           "vat": "N° TVA", "eori": "EORI", "inc": "Incoterm", "pay": "Conditions de paiement", "awb": "LTA n°",
           "bl": "Connaissement n°", "via": "Expédié par", "item": "N°", "ref": "Référence", "desc": "Désignation",
           "hs": "Code SH", "orig": "Orig.", "qty": "Qté", "unit": "Unité", "up": "Prix unitaire",
           "amt": "Montant", "goods": "Sous-total marchandises", "fret": "Fret", "assurance": "Assurance",
           "emballage": "Emballage", "remise": "Remise", "total": "TOTAL À PAYER", "gross": "Poids brut total",
           "net": "Poids net total", "pk": "Nombre de colis", "ptot": "Total page", "cur": "Devise",
           "page": "Page", "nw": "P. net kg", "decl": "Nous certifions la présente facture sincère et véritable.",
           "integ": "Établie par {c} pour le compte de l'expéditeur", "cartons": "cartons"},
    "es": {"facture": "FACTURA COMERCIAL", "pro_forma": "FACTURA PROFORMA",
           "valeur_douane_seulement": "FACTURA - VALOR SOLO PARA ADUANA",
           "facture_integrateur": "FACTURA COMERCIAL", "no": "Factura n.º", "date": "Fecha",
           "seller": "Vendedor / Exportador", "buyer": "Comprador / Facturar a", "consignee": "Consignatario",
           "vat": "N.º IVA", "eori": "EORI", "inc": "Incoterm", "pay": "Condiciones de pago", "awb": "Guía aérea n.º",
           "bl": "Conocimiento n.º", "via": "Enviado por", "item": "N.º", "ref": "Referencia",
           "desc": "Descripción", "hs": "Partida", "orig": "Orig.", "qty": "Cant.", "unit": "Ud.",
           "up": "Precio unit.", "amt": "Importe", "goods": "Subtotal mercancía", "fret": "Flete",
           "assurance": "Seguro", "emballage": "Embalaje", "remise": "Descuento", "total": "TOTAL",
           "gross": "Peso bruto total", "net": "Peso neto total", "pk": "Número de bultos",
           "ptot": "Total página", "cur": "Moneda", "page": "Página", "nw": "P. neto kg",
           "decl": "Certificamos que la presente factura es verdadera y correcta.",
           "integ": "Emitida por {c} por cuenta del remitente", "cartons": "cajas"},
}


def _date(ci):
    return {"en": d_en, "fr": d_fr, "es": d_es}[ci.language](ci.date) if ci.numstyle != "de" else d_dot(ci.date)


def _vat_print(v, spaced):
    if not v:
        return ""
    if spaced and v.startswith("FR"):
        return f"{v[:2]} {v[2:4]} {v[4:7]} {v[7:10]} {v[10:]}"
    return v


def render_ci(pen: Pen, ci, dm, style_seed: int):
    L = LBL[ci.language]
    ns = ci.numstyle
    dec = cur_decimals(ci.currency)
    style = ["boxed", "band", "plain"][style_seed % 3]
    pen.set_theme(["sans", "dejavu", "serif"][style_seed % 3] if style != "plain" else "lmono")
    rows_first = 13
    rows_next = 24
    lines = ci.lines
    pages = []
    i = 0
    first = True
    while i < len(lines) or not pages:
        n = rows_first if first else rows_next
        pages.append(lines[i:i + n])
        i += n
        first = False
    if len(pages[-1]) > (rows_first if len(pages) == 1 else rows_next) - 6 and len(lines) > rows_first:
        pages.append([])
    spaced = (style_seed // 3) % 5 == 0
    for pi, plines in enumerate(pages):
        if pi > 0:
            pen.new_page()
        y = _header(pen, ci, L, style, pi, len(pages), spaced)
        y = _lines_table(pen, ci, L, plines, y, style, dec, ns)
        if pi < len(pages) - 1:
            ptot = sum(l.amount for l in plines)
            pen.text(195, y + 5, f"{L['ptot']}: {ci.currency} {fmt_num(ptot, ns, dec)}", size=8.5, bold=True,
                     align="right")
        else:
            _totals(pen, ci, L, y, style, dec, ns)


def _header(pen, ci, L, style, pi, npages, spaced):
    title = L[ci.sous_type] if ci.sous_type in L else L["facture"]
    s = ci.seller
    if style == "band":
        pen.rect(0, 0, pen.W, 26, fill=BLUE, stroke=False)
        pen.text(12, 11, s.name, size=12, bold=True, color=LIGHT, maxw=120)
        pen.text(12, 17, ", ".join(s.addr), size=7.5, color=LIGHT, maxw=120)
        pen.text(198, 13, title, size=13, bold=True, align="right", color=LIGHT, maxw=70)
        y = 33
    elif style == "boxed":
        pen.text(12, 16, s.name, size=12, bold=True, maxw=110)
        pen.lines(12, 21, list(s.addr) + ([f"{L['vat']}: {s.vat}"] if s.vat else []), size=8)
        pen.rect(130, 9, 68, 16, lw=1)
        pen.text(164, 19, title, size=10.5, bold=True, align="center", maxw=66)
        y = 37
    else:
        pen.text(105, 14, title, size=13, bold=True, align="center")
        pen.text(12, 22, s.name, size=9.5, bold=True, maxw=120)
        pen.lines(12, 26, list(s.addr), size=8)
        y = 36
    if ci.sous_type == "facture_integrateur":
        pen.text(198, y - 3, L["integ"].format(c=ci.shipping_mode or "Express Démo Kilo (FICTIF)"), size=7,
                 align="right", color=GREY)
    # bloc références
    refs = [(L["no"], ci.numero), (L["date"], _date(ci)),
            (L["awb"] if ci.transport_kind == "awb" else L["bl"], ci.transport_ref),
            (L["inc"], f"{ci.incoterm} {ci.incoterm_place}"), (L["cur"], ci.currency),
            (L["pay"], ci.payment_terms)]
    if ci.shipping_mode:
        refs.append((L["via"], ci.shipping_mode))
    if npages > 1:
        refs.append((L["page"], f"{pi + 1}/{npages}"))
    x0 = 120
    for k, (a, b) in enumerate(refs):
        pen.text(x0, y + k * 4.2, f"{a}:", size=7.8, color=DARK)
        pen.text(x0 + 30, y + k * 4.2, b, size=7.8, bold=(k == 0), maxw=48)
    if pi == 0:
        b = ci.buyer
        pen.text(12, y, L["buyer"], size=7.5, color=GREY)
        blk = [b.name] + list(b.addr) + [f"{L['vat']}: {_vat_print(b.vat, spaced)}"]
        if ci.eori_printed:
            blk.append(f"{L['eori']}: {b.eori}")
        pen.lines(12, y + 4.5, blk, size=8.3, bold_first=True, maxw=100)
        if ci.consignee is not None:
            yy = y + 4.5 + len(blk) * 3.8 + 2
            pen.text(12, yy, L["consignee"], size=7.5, color=GREY)
            pen.lines(12, yy + 4.5, [ci.consignee.name] + list(ci.consignee.addr), size=8, maxw=100)
            return max(y + len(refs) * 4.2, yy + 16) + 6
        return max(y + len(refs) * 4.2, y + 4.5 + len(blk) * 3.8) + 6
    return y + len(refs) * 4.2 + 4


def _lines_table(pen, ci, L, plines, y, style, dec, ns):
    ul = UNIT_LABELS[ci.language]
    with_nw = style == "boxed"
    cols = [(L["item"], 7, "center"), (L["ref"], 23, "left"), (L["desc"], 45 if with_nw else 57, "left"),
            (L["hs"], 19, "center"), (L["orig"], 13, "center"), (L["qty"], 14, "right"), (L["unit"], 10, "center"),
            (L["up"], 20, "right"), (L["amt"], 24, "right")]
    if with_nw:
        cols.insert(7, (L["nw"], 12, "right"))
    rows = []
    for l in plines:
        r = [str(l.no), l.ref, l.desc, l.hs_printed or "", l.origin, fmt_qty(l.qty, ns), ul.get(l.unit, l.unit),
             fmt_num(l.price, ns, max(dec, 2) if dec else 0), fmt_num(l.amount, ns, dec)]
        if with_nw:
            r.insert(7, fmt_kg(l.net, ns))
        rows.append(r)
    grid = {"boxed": "full", "band": "h", "plain": "h"}[style]
    return pen.table(12, y, cols, rows, size=7.4, grid=grid, row_h=5.6)


def _totals(pen, ci, L, y, style, dec, ns):
    y += 4
    cur = ci.currency
    rows = []
    if ci.total_printed:
        if ci.footer:
            rows.append((L["goods"], ci.goods))
            for k in ("fret", "assurance", "emballage", "remise"):
                if k in ci.footer:
                    v = ci.footer[k]
                    rows.append((L[k], -v if k == "remise" else v))
        rows.append((L["total"], ci.total))
    # masses et colis à gauche, près des totaux (piège : ce ne sont pas des montants)
    wt = [f"{L['gross']}: {fmt_kg(ci.gross_total, ns)} kg", f"{L['net']}: {fmt_kg(ci.net_total, ns)} kg",
          f"{L['pk']}: {ci.packages} {L['cartons']}"]
    pen.lines(12, y + 2, wt, size=8, leading=4.3)
    for k, (lab, v) in enumerate(rows):
        last = k == len(rows) - 1
        yy = y + 2 + k * 4.8
        if last:
            pen.rect(118, yy - 3.8, 80, 6, fill=LIGHT, stroke=False)
        pen.text(120, yy, lab, size=8.5 if not last else 9.5, bold=last)
        pen.text(196, yy, f"{cur} {fmt_num(v, ns, dec)}", size=8.5 if not last else 9.5, bold=last, align="right")
    y = y + 6 + max(len(rows), 3) * 4.8 + 6
    pen.text(12, y, L["decl"], size=7.5, color=GREY)
    pen.text(150, y + 14, "______________________", size=8)
    pen.text(150, y + 18, "Authorised signature (FICTIF)", size=6.5, color=GREY)
